## TravisCI config
#
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
before_install:
    ## From: http://conda.pydata.org/docs/travis.htm
    ## Another one: https://gist.github.com/dan-blanchard/7045057
    #- sudo apt-get update
    - wget http://repo.continuum.io/miniconda/Miniconda3-3.7.0-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a	## Useful for debugging any conda issues
  
    - deps="`grep -v \# requirements/miniconda.txt`"
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION $deps
    - source activate test-environment

    - pip install nose -IU   ## Conda's nose is rotten, and `python setup.py nosetests` fails!
    - pip install lmfit      ## Workaround #149 or `setup.py install` violates sandbox!

install:
  - python setup.py install
  - pip install coveralls

# command to run tests
script:
    - if [[ $TRAVIS_PYTHON_VERSION = '3.4' ]]; then python setup.py doctest_docs; fi
    - if [[ $TRAVIS_PYTHON_VERSION = '3.4' ]]; then python setup.py doctest_code; fi
    - |
        if [[ $TRAVIS_PYTHON_VERSION = '2.7' ]]; then python setup.py test_code; fi
        if [[ $TRAVIS_PYTHON_VERSION = '3.3' ]]; then python setup.py test_code; fi
        if [[ $TRAVIS_PYTHON_VERSION = '3.4' ]]; then python setup.py test_code_cover; fi
    - python setup.py build_sphinx                  ## Build html-docs.
    - python setup.py sdist bdist_wheel             ## Create archives for PyPI repo.

    ## Ensure README valid ReST for PyPI.
    ##  In case it fails, improve the filtering-code in ``setup.py``.
    - python setup.py --long-description | rst2html.py  --halt=warning > /dev/null

after_success:
    coveralls

branches:
  only:
    - master

deploy:
    provider: pypi
    user: ankostis
    password:
        secure: AFaWbL5FIQHTAKxmFnOId1rApOsHxjpWGP3RVXTKjw65SJnRDoExne6Zd+M5ATRryBh2ud2ea3JK96mOl/CAZpr7fTpMHMnRruhyyQvJNKmOrXKBASmDF0yXoxuEaDNGO8BJ9sa0+S7sdoRiR/AzuDzRPHPzFR5J5DQiGCMHqmU=
    distributions: "sdist bdist_wheel"
    on:
        tags: true
        all_branches: true

